### ISSUE TITLE
runtime error produced

### ISSUE THREAD

**Issue by ReturnHttp402** [SAP/cf-mta-plugin#19]
version 2.0.0

using newest version instead of 1.0.2 to cf deploy gives me following error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7d516d]

goroutine 131 [running]:
github.com/SAP/cf-mta-plugin/clients/mtaclient.MtaRestClient.UploadMtaFile(0xbba8e0, 0xc0423706f0, 0xc04239e720, 0xc042479480, 0x902060, 0xc0424b4550, 0xc042445f48)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/clients/mtaclient/mta_rest_client.go:190 +0x18d
github.com/SAP/cf-mta-plugin/clients/mtaclient.(*MtaRestClient).UploadMtaFile(0xc04239e780, 0xc042479480, 0xc56420, 0xc0421f9040, 0x1200db0)
        <autogenerated>:12 +0x70
github.com/SAP/cf-mta-plugin/clients/mtaclient.RetryableMtaRestClient.UploadMtaFile.func1(0x0, 0xc0424b4550, 0xc0421f90f0, 0xc042445dd8)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/clients/mtaclient/retryable_mta_rest_client.go:120 +0x42
github.com/SAP/cf-mta-plugin/clients/baseclient.CallWithRetry(0xc0424028a0, 0x3, 0xb2d05e00, 0xc042445fa8, 0x1, 0x1, 0xc0423169f0)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/clients/baseclient/client_util.go:13 +0x43
github.com/SAP/cf-mta-plugin/clients/mtaclient.RetryableMtaRestClient.UploadMtaFile(0xbc3b60, 0xc04239e780, 0x3, 0xb2d05e00, 0xc042479480, 0x0, 0x0, 0x0)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/clients/mtaclient/retryable_mta_rest_client.go:122 +0xb0
github.com/SAP/cf-mta-plugin/clients/mtaclient.(*RetryableMtaRestClient).UploadMtaFile(0xc04239e7a0, 0xc042479480, 0x1, 0x1, 0xc042445fa8)
        <autogenerated>:38 +0x79
github.com/SAP/cf-mta-plugin/commands.uploadFilePart(0xc0422e6f78, 0xc04245d040, 0x3c, 0xbc3c00, 0xc04239e7a0, 0x0, 0x0, 0x0)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/commands/file_uploader.go:177 +0x87
github.com/SAP/cf-mta-plugin/commands.uploadInChunks.func1(0x8, 0x9811f0)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/commands/file_uploader.go:128 +0x69
github.com/SAP/cf-mta-plugin/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc04246e9c0, 0xc04227cab0)
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x5e
created by github.com/SAP/cf-mta-plugin/vendor/golang.org/x/sync/errgroup.(*Group).Go
        C:/prj/root/go-workspace/src/github.com/SAP/cf-mta-plugin/vendor/golang.org/x/sync/errgroup/errgroup.go:66 +0x6d

**Comment by mptsonev** [comment]
Thanks for reporting. This is fixed in version 2.0.3 with commit: https://github.com/SAP/cf-mta-plugin/commit/8af687f128e9af195c1f510da6b427edbd06fb2e
