### ISSUE TITLE
Usage of deploy command

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP/cf-mta-plugin#22]
Hi

Can you please help me on this issue: https://github.wdf.sap.corp/D032102/MultiTenantShoppingListWithHanaAnalyticsAdapter/issues/1 

Its an issue about how to use deploy. I tried with below command and getting an error:

`cf deploy MTA -e <path-to-the-yaml-file>`

Error is:

<img width="1584" alt="screen shot 2018-03-13 at 9 31 18 am" src="https://user-images.githubusercontent.com/6059076/37322117-b5ac5866-26a1-11e8-9494-21ac0f9ff9e0.png">

**Comment by mptsonev** [comment]
You have to specify the *path* to the mta archive you want to deploy.
